title = "AlterOwn - A Young Entrepreneur's Journey"
baseURL = "/hugo-website"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.6
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "A Young Entrepreneur's Journey"
  facebook = "https://facebook.com/alterownfb"
  twitter = ""
  instagram = "https://instagram.com/alterown"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "https://www.instagram.com/p/B-WnQTwjTz9/"
  recent_posts_number = 2
